version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  service-registry:
    image: your-docker-hub-username/serviceregistry:latest
    container_name: service-registry
    restart: always
    depends_on:
      - kafka
    ports:
      - "8761:8761"  # Adjust port if needed
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    image: your-docker-hub-username/apigateway:latest
    container_name: api-gateway
    restart: always
    depends_on:
      - service-registry
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  customer-service:
    image: your-docker-hub-username/customer:latest
    container_name: customer-service
    restart: always
    depends_on:
      - kafka
      - service-registry
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BROKER: kafka:9092

  cart-service:
    image: your-docker-hub-username/cart:latest
    container_name: cart-service
    restart: always
    depends_on:
      - kafka
      - service-registry
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BROKER: kafka:9092

  shipping-service:
    image: your-docker-hub-username/shipping:latest
    container_name: shipping-service
    restart: always
    depends_on:
      - kafka
      - service-registry
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BROKER: kafka:9092
